# Generated by Django 5.0.6 on 2024-05-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
